# Daily Heating Cycle Counter and Duration Tracker
# Add this to your Home Assistant configuration.yaml

# =============================================================================
# COUNTERS - Track daily heating cycles
# =============================================================================
counter:
  # Daily heating cycle counter for your EPH Ember zone
  zone_one_heating_cycles_today:
    name: "Zone ONE Heating Cycles Today"
    icon: mdi:fire
    
  # Total daily heating cycles (same as zone one since you have one zone)
  total_heating_cycles_today:
    name: "Total Heating Cycles Today"
    icon: mdi:counter

# =============================================================================
# INPUT DATETIME - Track heating session start times
# =============================================================================
input_datetime:
  zone_one_heating_start:
    name: "Zone ONE Last Heating Start"
    has_date: true
    has_time: true

# =============================================================================
# INPUT NUMBER - Store heating durations for averaging
# =============================================================================
input_number:
  # Store total heating time for averaging
  zone_one_total_heating_time_today:
    name: "Zone ONE Total Heating Time Today"
    min: 0
    max: 1440  # Max 24 hours in minutes
    unit_of_measurement: "min"

# =============================================================================
# TEMPLATE SENSORS - Calculate averages and statistics
# =============================================================================
template:
  - binary_sensor:
      # Detect when heating is actively on for Zone ONE
      - name: "Zone ONE Heating Active"
        state: >
          {% set climate_state = states('climate.one') %}
          {% set hvac_action = state_attr('climate.one', 'hvac_action') %}
          {% if climate_state in ['heat', 'heating'] or hvac_action == 'heating' %}
            on
          {% else %}
            off
          {% endif %}
        device_class: heat

  - sensor:
      # Average heating duration per cycle
      - name: "Zone ONE Average Heating Duration"
        state: >
          {% set cycles = states('counter.zone_one_heating_cycles_today') | int %}
          {% set total_time = states('input_number.zone_one_total_heating_time_today') | float %}
          {% if cycles > 0 %}
            {{ (total_time / cycles) | round(1) }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "min"
        icon: mdi:clock-outline
        
      # Daily heating efficiency metrics
      - name: "Daily Heating Efficiency Zone ONE"
        state: >
          {% set avg_duration = states('sensor.zone_one_average_heating_duration') | float %}
          {% set cycles = states('counter.zone_one_heating_cycles_today') | int %}
          {% if cycles > 0 %}
            {% if avg_duration < 10 %}
              Poor
            {% elif avg_duration < 20 %}
              Good
            {% else %}
              Excellent
            {% endif %}
          {% else %}
            No Data
          {% endif %}
        icon: mdi:speedometer
        
      # Total heating statistics (same as zone one since you have one zone)
      - name: "Total Daily Heating Cycles"
        state: >
          {{ states('counter.zone_one_heating_cycles_today') | int }}
        unit_of_measurement: "cycles"
        icon: mdi:counter
        
      - name: "Total Daily Heating Time"
        state: >
          {{ states('input_number.zone_one_total_heating_time_today') | float }}
        unit_of_measurement: "min"
        icon: mdi:clock

# =============================================================================
# HISTORY STATS - Alternative method for tracking heating time
# =============================================================================
sensor:
  # Track actual heating time using history_stats
  - platform: history_stats
    name: Zone ONE Heating Time Today
    entity_id: binary_sensor.zone_one_heating_active
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}'
    end: '{{ now() }}'
    
  # Count heating cycles using history_stats
  - platform: history_stats
    name: Zone ONE Heating Cycles Count Today
    entity_id: binary_sensor.zone_one_heating_active
    state: 'on'
    type: count
    start: '{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}'
    end: '{{ now() }}'