# Enhanced Heating Detection for PyEphEmber2
# Updated binary sensor with multiple detection methods

# =============================================================================
# ROBUST HEATING DETECTION - Multiple methods for reliability
# =============================================================================
binary_sensor:
  # Primary heating detection - multiple fallback methods
  - platform: template
    sensors:
      zone_one_heating_active:
        friendly_name: "Zone ONE Heating Active"
        device_class: heat
        value_template: >
          {# Method 1: Check hvac_action attribute #}
          {% set hvac_action = state_attr('climate.castle_thermostat', 'hvac_action') %}
          
          {# Method 2: Check current vs target temperature with heating mode #}
          {% set current_temp = state_attr('climate.castle_thermostat', 'current_temperature') %}
          {% set target_temp = state_attr('climate.castle_thermostat', 'temperature') %}
          {% set hvac_mode = state_attr('climate.castle_thermostat', 'hvac_mode') %}
          
          {# Method 3: Check if climate entity shows 'heat' state #}
          {% set climate_state = states('climate.castle_thermostat') %}
          
          {# Primary detection: hvac_action #}
          {% if hvac_action == 'heating' %}
            true
          {# Fallback 1: heating mode + temp difference #}
          {% elif hvac_mode == 'heat' and current_temp is not none and target_temp is not none %}
            {{ (target_temp | float) > (current_temp | float) and (target_temp | float - current_temp | float) > 0.5 }}
          {# Fallback 2: climate entity state #}
          {% elif climate_state == 'heat' %}
            true
          {# Default: not heating #}
          {% else %}
            false
          {% endif %}
          
        icon_template: >
          {% if is_state('binary_sensor.zone_one_heating_active', 'on') %}
            mdi:fire
          {% else %}
            mdi:radiator-disabled
          {% endif %}
        
        # Additional attributes for debugging
        attribute_templates:
          hvac_action: "{{ state_attr('climate.castle_thermostat', 'hvac_action') }}"
          hvac_mode: "{{ state_attr('climate.castle_thermostat', 'hvac_mode') }}"
          current_temp: "{{ state_attr('climate.castle_thermostat', 'current_temperature') }}"
          target_temp: "{{ state_attr('climate.castle_thermostat', 'temperature') }}"
          climate_state: "{{ states('climate.castle_thermostat') }}"
          temp_difference: >
            {% set current = state_attr('climate.castle_thermostat', 'current_temperature') %}
            {% set target = state_attr('climate.castle_thermostat', 'temperature') %}
            {% if current is not none and target is not none %}
              {{ (target | float - current | float) | round(1) }}
            {% else %}
              "unknown"
            {% endif %}

# =============================================================================
# ALTERNATIVE HEATING DETECTION METHODS
# =============================================================================
  # Alternative method 1: Direct API polling (if needed)
  - platform: template
    sensors:
      zone_one_heating_api_check:
        friendly_name: "Zone ONE Heating (API Check)"
        device_class: heat
        value_template: >
          {# This would require a custom sensor that polls the EPH API directly #}
          {# For now, we'll use the climate entity as fallback #}
          {{ is_state_attr('climate.castle_thermostat', 'hvac_action', 'heating') or 
             (is_state_attr('climate.castle_thermostat', 'hvac_mode', 'heat') and 
              state_attr('climate.castle_thermostat', 'current_temperature') | float < 
              state_attr('climate.castle_thermostat', 'temperature') | float - 0.5) }}
              
  # Alternative method 2: Temperature trend detection
  - platform: template
    sensors:
      zone_one_heating_trend:
        friendly_name: "Zone ONE Heating (Trend Detection)"
        device_class: heat
        value_template: >
          {# Check if temperature is rising when in heat mode #}
          {% set mode = state_attr('climate.castle_thermostat', 'hvac_mode') %}
          {% set current = state_attr('climate.castle_thermostat', 'current_temperature') %}
          {% set target = state_attr('climate.castle_thermostat', 'temperature') %}
          
          {% if mode == 'heat' and current is not none and target is not none %}
            {{ current | float < target | float }}
          {% else %}
            false
          {% endif %}

# =============================================================================
# DEBUGGING SENSORS - To help troubleshoot PyEphEmber2 changes
# =============================================================================
sensor:
  # Debug sensor to show all climate attributes
  - platform: template
    sensors:
      climate_one_debug:
        friendly_name: "Climate ONE Debug Info"
        value_template: >
          State: {{ states('climate.castle_thermostat') }} | 
          Action: {{ state_attr('climate.castle_thermostat', 'hvac_action') }} | 
          Mode: {{ state_attr('climate.castle_thermostat', 'hvac_mode') }} | 
          Current: {{ state_attr('climate.castle_thermostat', 'current_temperature') }}°C | 
          Target: {{ state_attr('climate.castle_thermostat', 'temperature') }}°C
        icon_template: mdi:information

template:
  - sensor:
      # Enhanced debug sensor with all available attributes
      - name: "PyEphEmber2 Debug Status"
        state: >
          {% set attrs = state_attr('climate.castle_thermostat', 'attribution') %}
          {{ states('climate.castle_thermostat') }}
        attributes:
          all_attributes: >
            {% set attrs = state_attr('climate.castle_thermostat', 'hvac_action') %}
            {% if attrs is not none %}All attributes available{% else %}No attributes found{% endif %}
          hvac_action: "{{ state_attr('climate.castle_thermostat', 'hvac_action') | default('unknown', true) }}"
          hvac_modes: "{{ state_attr('climate.castle_thermostat', 'hvac_modes') | default('unknown', true) }}"
          current_temperature: "{{ state_attr('climate.castle_thermostat', 'current_temperature') | default('unknown', true) }}"
          temperature: "{{ state_attr('climate.castle_thermostat', 'temperature') | default('unknown', true) }}"
          min_temp: "{{ state_attr('climate.castle_thermostat', 'min_temp') | default('unknown', true) }}"
          max_temp: "{{ state_attr('climate.castle_thermostat', 'max_temp') | default('unknown', true) }}"
          target_temp_step: "{{ state_attr('climate.castle_thermostat', 'target_temp_step') | default('unknown', true) }}"
          supported_features: "{{ state_attr('climate.castle_thermostat', 'supported_features') | default('unknown', true) }}"
        icon: mdi:bug

# =============================================================================
# AUTOMATION TO LOG CHANGES - Helps detect PyEphEmber2 behavior
# =============================================================================
automation:
  - id: log_climate_changes
    alias: "Log Climate Entity Changes"
    description: "Log all changes to climate.one for debugging PyEphEmber2"
    trigger:
      - platform: state
        entity_id: climate.castle_thermostat
    action:
      - service: logbook.log
        data:
          name: "PyEphEmber2 Debug"
          message: >
            Climate changed: {{ trigger.from_state.state if trigger.from_state else 'unknown' }} → {{ trigger.to_state.state if trigger.to_state else 'unknown' }}
            Action: {{ trigger.from_state.attributes.hvac_action if trigger.from_state and trigger.from_state.attributes else 'unknown' }} → {{ trigger.to_state.attributes.hvac_action if trigger.to_state and trigger.to_state.attributes else 'unknown' }}
            Mode: {{ trigger.from_state.attributes.hvac_mode if trigger.from_state and trigger.from_state.attributes and 'hvac_mode' in trigger.from_state.attributes else 'unknown' }} → {{ trigger.to_state.attributes.hvac_mode if trigger.to_state and trigger.to_state.attributes and 'hvac_mode' in trigger.to_state.attributes else 'unknown' }}
            Temp: {{ trigger.from_state.attributes.current_temperature if trigger.from_state and trigger.from_state.attributes else 'unknown' }}°C → {{ trigger.to_state.attributes.current_temperature if trigger.to_state and trigger.to_state.attributes else 'unknown' }}°C
            Target: {{ trigger.from_state.attributes.temperature if trigger.from_state and trigger.from_state.attributes else 'unknown' }}°C → {{ trigger.to_state.attributes.temperature if trigger.to_state and trigger.to_state.attributes else 'unknown' }}°C
          entity_id: climate.castle_thermostat

  - id: log_heating_detection_changes
    alias: "Log Heating Detection Changes"
    description: "Log when our heating detection changes state"
    trigger:
      - platform: state
        entity_id: binary_sensor.zone_one_heating_active
    action:
      - service: logbook.log
        data:
          name: "Heating Detection"
          message: >
            Heating detection: {{ trigger.from_state.state }} → {{ trigger.to_state.state }}
            Climate state: {{ states('climate.castle_thermostat') }}
            HVAC Action: {{ state_attr('climate.castle_thermostat', 'hvac_action') }}
            Debug info: {{ states('sensor.climate_one_debug') }}